# Generated by Django 2.2.2 on 2019-10-09 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='종목코드')),
                ('name', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='종목명')),
                ('sector', models.CharField(blank=True, max_length=50, null=True, verbose_name='섹터')),
                ('industry', models.TextField(null=True, verbose_name='섹터상세')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=10, verbose_name='날짜')),
                ('code', models.CharField(max_length=10, verbose_name='종목코드')),
                ('freq', models.CharField(max_length=5, verbose_name='주기')),
                ('gubun', models.CharField(max_length=5, verbose_name='구분')),
                ('sale', models.FloatField(null=True, verbose_name='매출액')),
                ('profit', models.FloatField(null=True, verbose_name='영업이익')),
                ('netincome', models.FloatField(null=True, verbose_name='당기순이익')),
                ('d_netincome', models.FloatField(null=True, verbose_name='지배순이익')),
                ('b_netincome', models.FloatField(null=True, verbose_name='비지배순이익')),
                ('asset', models.FloatField(null=True, verbose_name='자산총계')),
                ('liability', models.FloatField(null=True, verbose_name='부채총계')),
                ('equity', models.FloatField(null=True, verbose_name='자본총계')),
                ('d_equity', models.FloatField(null=True, verbose_name='지배순지분')),
                ('b_equity', models.FloatField(null=True, verbose_name='비지배지분')),
                ('equity_stock', models.FloatField(null=True, verbose_name='자본금')),
            ],
            options={
                'verbose_name': '재무정보',
                'verbose_name_plural': '재무정보 테이블',
                'unique_together': {('date', 'code', 'freq', 'gubun')},
            },
        ),
        migrations.CreateModel(
            name='CompanyExtr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=10, verbose_name='날짜')),
                ('code', models.CharField(max_length=10, verbose_name='종목코드')),
                ('freq', models.CharField(max_length=5, verbose_name='주기')),
                ('d_eps', models.FloatField(null=True, verbose_name='연결EPS')),
                ('b_eps', models.FloatField(null=True, verbose_name='개별EPS')),
                ('per', models.FloatField(null=True, verbose_name='PER')),
                ('bps', models.FloatField(null=True, verbose_name='BPS')),
                ('pbr', models.FloatField(null=True, verbose_name='PBR')),
                ('dps', models.FloatField(null=True, verbose_name='DPS')),
                ('dps_rate', models.FloatField(null=True, verbose_name='배당수익률')),
                ('roe', models.FloatField(null=True, verbose_name='ROE')),
                ('netincome_rate', models.FloatField(null=True, verbose_name='순이익률')),
                ('profit_rate', models.FloatField(null=True, verbose_name='영업이익률')),
                ('price', models.FloatField(null=True, verbose_name='주가')),
            ],
            options={
                'verbose_name': '재무비율',
                'verbose_name_plural': '재무비율 테이블',
                'unique_together': {('date', 'code', 'freq')},
            },
        ),
    ]
