# Generated by Django 2.2.2 on 2019-10-29 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nameapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kosdaq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(max_length=10, verbose_name='날짜')),
                ('code', models.CharField(max_length=10, verbose_name='코드')),
                ('open', models.FloatField(null=True, verbose_name='시가')),
                ('high', models.FloatField(null=True, verbose_name='고가')),
                ('low', models.FloatField(null=True, verbose_name='저가')),
                ('close', models.FloatField(null=True, verbose_name='종가')),
                ('volume', models.FloatField(null=True, verbose_name='거래량')),
                ('total', models.FloatField(null=True, verbose_name='시가총액')),
                ('shares', models.FloatField(null=True, verbose_name='주식수')),
            ],
            options={
                'verbose_name': '코스닥',
                'verbose_name_plural': '코스닥 기초정보 테이블',
                'ordering': ('code',),
                'unique_together': {('date', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Kospi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(max_length=10, verbose_name='날짜')),
                ('code', models.CharField(max_length=10, verbose_name='코드')),
                ('open', models.FloatField(null=True, verbose_name='시가')),
                ('high', models.FloatField(null=True, verbose_name='고가')),
                ('low', models.FloatField(null=True, verbose_name='저가')),
                ('close', models.FloatField(null=True, verbose_name='종가')),
                ('volume', models.FloatField(null=True, verbose_name='거래량')),
                ('total', models.FloatField(null=True, verbose_name='시가총액')),
                ('shares', models.FloatField(null=True, verbose_name='주식수')),
            ],
            options={
                'verbose_name': '코스피',
                'verbose_name_plural': '코스피 기초정보 테이블',
                'ordering': ('code',),
                'unique_together': {('date', 'code')},
            },
        ),
        migrations.CreateModel(
            name='StockTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='종목코드')),
                ('name', models.CharField(max_length=20, verbose_name='종목명')),
                ('sector', models.CharField(max_length=100, null=True, verbose_name='산업구분(KRX)')),
                ('industry', models.CharField(max_length=100, null=True, verbose_name='주요제품(KRX)')),
                ('division', models.CharField(max_length=10, verbose_name='구분')),
            ],
        ),
        migrations.DeleteModel(
            name='Stock',
        ),
    ]
