# Generated by Django 2.2.6 on 2019-11-14 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nameapp', '0002_auto_20191029_1425'),
    ]

    operations = [
        migrations.CreateModel(
            name='KospiPredict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(max_length=10, unique=True, verbose_name='날짜')),
                ('close', models.FloatField(null=True, verbose_name='종가')),
                ('open', models.FloatField(null=True, verbose_name='시가')),
                ('real_return', models.FloatField(null=True, verbose_name='실제값')),
                ('pred_return', models.FloatField(null=True, verbose_name='예측값')),
                ('signal', models.IntegerField(null=True, verbose_name='매매신호')),
            ],
            options={
                'verbose_name': '코스피 예측',
                'verbose_name_plural': '코스피 예측정보 테이블',
            },
        ),
    ]
