# Generated by Django 2.2.6 on 2019-11-26 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nameapp', '0003_kospipredict'),
    ]

    operations = [
        migrations.AddField(
            model_name='kospipredict',
            name='buy',
            field=models.IntegerField(null=True, verbose_name='매수시점'),
        ),
        migrations.AddField(
            model_name='kospipredict',
            name='sell',
            field=models.IntegerField(null=True, verbose_name='매도시점'),
        ),
    ]
